[project]
name = "zoom-rag-agent"
version = "0.1.0"
description = "A RAG agent used in Zoom"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cadwyn>=4.2.4",
    "fastapi[standard]>=0.115.0",
    "llama-index>=0.11.13",
    "llama-index-core>=0.11.12",
    "llama-index-embeddings-jinaai>=0.3.1",
    "llama-index-llms-together>=0.2.0",
    "llama-index-vector-stores-qdrant>=0.3.0",
    "orjson>=3.10.7",
    "pydantic>=2.9.2",
    "python-dotenv>=1.0.1",
]

[tool.uv]
dev-dependencies = [
    "llama-index-utils-workflow>=0.2.1",
    "pytest>=8.3.3",
]
