services:
  app:
    container_name: chatbot-api
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
    network_mode: host
    env_file: "../.env"

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    network_mode: host
    env_file: "../.env"
    command: http --url=strong-serval-cunning.ngrok-free.app 8000

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    network_mode: host
    environment:
      - QDRANT_HTTP_PORT=6333
      - QDRANT_GRPC_PORT=6334
